
package paraisoTropical;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maiana
 */
public class AssentosDisponiveis extends javax.swing.JFrame {

    private int poltronaSelecionada;
    private int VooAtual;
    private static final long serialVersionUID = 1L;
    static String hor,dat,dest,orige,quantAss;
        

    public void setVooAtual(int l) {
        this.VooAtual = l;
    }

    public void setDestino(String a) {
        destino.setText(a);
        this.dest = a;
    }

    public void setOrigem(String a) {
        origem.setText(a);
        this.orige = a;
    }

    public void setEscala(String a) {
        escala.setText(a);
    }

    public void setData(String a) {
        data.setText(a);
        this.dat = a;
    }

    public void setHorario(String a) {
        horario.setText(a);
        this.hor = a;
    }

    public void qtdAssentos(Passageiro[] p) {

        for (Passageiro x : p) { //para cada assento do vetor de passageiros que contem os assentos
            if (!x.cadOcupada()) // se ocupada for false, ou seja se estiver livre
            {
                assentosdisp.addItem(Integer.toString(x.getNumero() + 1)); // bota no combobox de assentos disponiveis o numero da poltrona
            }
        }
    }

    public AssentosDisponiveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        buttonGrouppag = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        escala = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        origem = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        horario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        opdinheiro = new javax.swing.JRadioButton();
        opcartao = new javax.swing.JRadioButton();
        opdebito = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldnome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextcpf = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        assentosdisp = new javax.swing.JComboBox<>();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Origem:");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Destino:");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Escala:");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Data:");

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Horario:");

        jLabel12.setText("Escolha o assento:");

        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("VALOR:");

        jLabel15.setText("Escolha a Forma de Pagamento:");

        buttonGrouppag.add(opdinheiro);
        opdinheiro.setText("Dinheiro");
        opdinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opdinheiroActionPerformed(evt);
            }
        });

        buttonGrouppag.add(opcartao);
        opcartao.setText("Cartao de Credito");
        opcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcartaoActionPerformed(evt);
            }
        });

        buttonGrouppag.add(opdebito);
        opdebito.setText("Cartão de Débito");
        opdebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opdebitoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados passageiro:"));

        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF:");

        jLabel16.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirma.setText("Confirmar");
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        assentosdisp.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                assentosdispPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        assentosdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assentosdispActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(confirma)
                                .addGap(34, 34, 34)
                                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(opdinheiro)
                                        .addGap(18, 18, 18)
                                        .addComponent(opcartao)
                                        .addGap(29, 29, 29)
                                        .addComponent(opdebito))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(assentosdisp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(horario, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(origem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(escala, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(escala, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9))
                            .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(assentosdisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opdinheiro)
                    .addComponent(opcartao)
                    .addComponent(opdebito))
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirma)
                    .addComponent(voltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        //try {
            this.setVisible(false);
            //JOptionPane.showMessageDialog(null, "Boa Viagem!");
            TelaPercursoVoo o = new TelaPercursoVoo();
            o.ocupa(VooAtual, poltronaSelecionada, jTextFieldnome.getText(), jTextcpf.getText());

            // String origem = o.getDestino(); //escolha.get(0).getOrigem();
            // criação do documento
            Document document = new Document();
            double x = Math.random() * 0x3e8;
            String arquivo = "E-TICKET" + origem.getText() + destino.getText() + x + ".pdf"; //cria um nome de arquivo aleatório
            // Com o nome aleatório cada execução gerará um pdf novo e diferente.
            try {

                PdfWriter.getInstance(document, new FileOutputStream(arquivo)); //utliza o nome do arquivo aleatório
                document.open();
                Image logo = Image.getInstance("logoeticket1.jpeg");  // coloca o Logo no pdf
                document.add(logo);
                // adicionando um parágrafo no documento
                Paragraph p = new Paragraph("");
                p.setAlignment(1);
                document.add(p);
                p = new Paragraph("");
                document.add(p);
                p = new Paragraph("ETICKET - " + Math.random());
                document.add(p);
                p = new Paragraph("\n\n");
                document.add(p);
                p = new Paragraph("Dados do Passageiro:");
                document.add(p);
                p = new Paragraph("Nome: " + jTextFieldnome.getText());
                document.add(p);
                p = new Paragraph("CPF: " + jTextcpf.getText());
                document.add(p);
                p = new Paragraph("\n\n");
                document.add(p);
                p = new Paragraph("Dados do Vôo: ");
                document.add(p);
                p = new Paragraph("Origem: " + origem.getText());
                document.add(p);
                p = new Paragraph("Destino: " + destino.getText());
                document.add(p);
                p = new Paragraph("Escala: " + escala.getText());
                document.add(p);
                p = new Paragraph("Data: " + data.getText());
                document.add(p);
                p = new Paragraph("Horario: " + horario.getText());
                document.add(p);
                p = new Paragraph("Assento: " + assentosdisp.getSelectedItem().toString());
                document.add(p);
            } catch (DocumentException de) {
                System.err.println(de.getMessage());
            } catch (IOException ioe) {
                System.err.println(ioe.getMessage());
            }
            //fechando pdf
            document.close();

            try {
                Desktop.getDesktop().open(new File(arquivo));
            } catch (IOException ex) {
                Logger.getLogger(AssentosDisponiveis.class.getName()).log(Level.SEVERE, null, ex);
            }
            //new TelaPrincipal().setVisible(true);
            TelaPrincipal o1 = new TelaPrincipal();
            o1.setLocation(2, 31);
            o1.setVisible(true);
        /*}catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Apenas números inteiros positivos");
        }*/
    }//GEN-LAST:event_confirmaActionPerformed

    private void opdinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opdinheiroActionPerformed
        Voos v = new Voos();
        String texto = String.valueOf(v.valor(this.dest,this.orige,this.dat,this.hor));
        double valor = Double.parseDouble(texto);
        DecimalFormat df = new DecimalFormat("###,##0.00");
        texto = df.format(valor);
        jLabel14.setText(texto);
        new ConfirmaçãoMatricula().setVisible(true);
        
    }//GEN-LAST:event_opdinheiroActionPerformed

    private void opcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcartaoActionPerformed
        Voos v = new Voos();
        String texto = String.valueOf(v.valor(this.dest,this.orige,this.dat,this.hor));
        double valor = Double.parseDouble(texto);
        DecimalFormat df = new DecimalFormat("###,##0.00");
        texto = df.format(valor);
        jLabel14.setText(texto);
        new PagamentoCartao().setVisible(true);

    }//GEN-LAST:event_opcartaoActionPerformed

    private void opdebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opdebitoActionPerformed
        Voos v = new Voos();
        String texto = String.valueOf(v.valor(this.dest,this.orige,this.dat,this.hor));
        double valor = Double.parseDouble(texto);
        DecimalFormat df = new DecimalFormat("###,##0.00");
        texto = df.format(valor);
        jLabel14.setText(texto);
        new PagamentoCartao().setVisible(true);
       
        

    }//GEN-LAST:event_opdebitoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.setVisible(false);
        //new TelaPercursoVoo().setVisible(true);
        TelaPercursoVoo o1 = new TelaPercursoVoo();
        o1.setLocation(2, 31);
        o1.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void assentosdispPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_assentosdispPopupMenuWillBecomeInvisible
        this.poltronaSelecionada = Integer.parseInt(assentosdisp.getSelectedItem().toString()) - 1;
    }//GEN-LAST:event_assentosdispPopupMenuWillBecomeInvisible

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed

    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void assentosdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assentosdispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assentosdispActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssentosDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssentosDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssentosDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssentosDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssentosDisponiveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> assentosdisp;
    private javax.swing.ButtonGroup buttonGrouppag;
    private javax.swing.JButton confirma;
    private javax.swing.JLabel data;
    public javax.swing.JLabel destino;
    private javax.swing.JLabel escala;
    private javax.swing.JLabel horario;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextcpf;
    private javax.swing.JRadioButton opcartao;
    private javax.swing.JRadioButton opdebito;
    private javax.swing.JRadioButton opdinheiro;
    private javax.swing.JLabel origem;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
